Fixed issue with failed compilation due to undefined reference to class in the dictionnary. The SelDict.cc is now correctly generated and added to the source list for compilation